Models/Entities/SpareParts.cs
using BIRC.Models.Repositories;
using System;
using System.ComponentModel.DataAnnotations;


namespace BIRC.Models.Entities
{
    public class SpareParts : BaseModel
    {
        [Display(Name = "Product Number")]
        public string PartNumber { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int Quantity { get; set; }

        [Display(Name = "Incoming")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime DtIn { get; set; }
              
        [Display(Name = "Storage Bin")]
        public string Location { get; set; }

        [StringLength(20)]
        [Display(Name = "Purchase Order")]
        public string PurchaseOrder { get; set; }
        public string LocalUsed { get; set; }
        public int minimumQuantity { get; set; }
        public string UserId { get; set; }

    }
}

ViewModels/ReportGeralViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BIRC.ViewModels
{
    public class ReportGeralViewModel
    {
        
        public DateTime FromDate { get; set; }
        
        public DateTime ToDate { get; set; }

        public string TypeReport { get; set; }
    }
}

Controllers/LogUpdateController.cs
using BIRC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BIRC.Controllers
{
    public class LogUpdateController : Controller
    {
        private readonly Contexto _context;

        public LogUpdateController(Contexto contexto)
        {
            _context = contexto;
        }     

        // GET: LogUpdate
        public IActionResult Index()
        {            
            return View();
        }
                
        public IActionResult Csv()
        {
            StringBuilder builder = new StringBuilder();

            builder.AppendLine("REGISTRO;COD PRODUTO;PRODUTO;MOVIMENTACAO;CATEGORIA;SALDO ATUAL;DATA DE MOVIMENTACAO;LOCAL USADO;USUARIO;QUANTIDADE MINIMA") ;


             var dataLog = _context.VwLogUpdate.Distinct().ToList();

            foreach (var user in dataLog)
            {
                
                builder.AppendLine($"{user.Id};{user.CodProduto};{user.NomeProduto};{user.MovimentacaoSaldo};{user.CategoriaProduto};{user.SaldoAtual};{user.DataMovimentacao};{user.LocalUsed};{user.NomeUsuario};{user.minimumQuantity}");
            }

            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "RelatorioGerals.csv");//gera o arquivo csv 
        }                      

    }
}

Controllers/SparePartsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using BIRC.Models;
using BIRC.Models.Entities;
using BIRC.Helper;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BIRC.Controllers
{
    public class SparePartsController : Controller
    {
        public readonly Contexto _contexto;
        public readonly QueryHelper<SpareParts> _helper;

        public SparePartsController(Contexto context)
        {
            _contexto = context;
            _helper = new QueryHelper<SpareParts>(context);
        }
        // GET: SpareOfficeController ( Ordenado Descending )
        public IActionResult SpareMenu()
        {
            return View();
        }
        public IActionResult Index()
        {
            var spareparts = _contexto.SpareParts.OrderByDescending(x => x.Id).ToList();
            return View(spareparts);

        }

        [HttpPost]
        public ActionResult Index(string searchString, string search)
        {
            //var spare = from s in _contexto.SpareParts select s;
            var recebeSearch = search;

            if (String.IsNullOrEmpty(searchString))
            {
                return RedirectToAction("Index");
            }
            if (searchString.Equals("Partnumber"))
            {
                var spare = _contexto.SpareParts.Where(s => s.PartNumber.Contains(search)).ToList();
                return View(spare);
            }

            return View();

        }

        // GET: SpareParts/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //POST: SpareRepairer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SpareParts spareparts)
        {
            try
            {

                string productNameUpper = spareparts.PartNumber.ToUpper();
                string descriptionUpper = spareparts.Description.ToUpper();

                spareparts.PartNumber = productNameUpper;
                spareparts.Description = descriptionUpper;

                if (ModelState.IsValid)
                {
                    spareparts.Id = _helper.GetMaxId();
                    _contexto.SpareParts.Add(spareparts);
                    _contexto.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(spareparts);
            }
            catch
            {
                return View();
            }
        }

        // GET: SpareRepairers/Edit/5
        public async Task<IActionResult> EditItem(int? id)
        {
            if (id != null)
            {
                return NotFound();
            }
            var spareParts = await _contexto.SpareParts.FindAsync(id);
            if (spareParts == null)
            {
                return NotFound();
            }
            return View(spareParts);

        }

        // POST: SparePartes/Edit/5
        [HttpPost]
        public ActionResult EditItem(string id, string partNumber, string description, string quantity,string minimumQuantity, string value, string dtIn, string location, string currentBalance, string po, string typeedtion, string localUsed, string userId)
        {

            int qtyFormated = 0;
            //MODELO DE NEGOCIO
            if (typeedtion.Equals("minus"))
            {
                qtyFormated = int.Parse(value) - int.Parse(quantity);
            }
            else
            {
                qtyFormated = int.Parse(value) + int.Parse(quantity);
            }

            SpareParts spareParts = new SpareParts
            {
                Id = int.Parse(id),
                PartNumber = partNumber.ToUpper().ToString(),
                Description = description.ToUpper().ToString(),
                Quantity = qtyFormated,
                minimumQuantity = int.Parse(minimumQuantity),//implementado 060323
                PurchaseOrder = po,
                Location = location,
                DtIn = DateTime.Parse(dtIn),
                LocalUsed = localUsed,
                UserId = userId
            };

            LogUpdate logUpdate = new LogUpdate
            {
                Id = int.Parse(id),
                Alteration = DateTime.Now,
                Quantity = int.Parse(quantity),
                minimumQuantity = int.Parse(minimumQuantity),//implementado 060323
                Product = partNumber,
                TypeEdtion = typeedtion,
                UserId = userId,
                CurrentBalance = qtyFormated,
                LocalUsed = localUsed,
                ModelAlteration = "SpareParts",


            };

            if (ModelState.IsValid)
            {
                if (id != null)
                {
                    _contexto.Update(spareParts);
                    _contexto.SaveChangesAsync();
                    _contexto.LogUpdate.AddAsync(logUpdate);
                    _contexto.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else return View(spareParts);
            }
            return NotFound();
        }


        public ActionResult ReportGeral()
        {

            return View();
        }

        public IActionResult Csv()
        {
            var builder = new StringBuilder();

            builder.AppendLine("PRODUCT NAME;QUANTITY;LOCATION;USUARIO");

            var dataLog = _contexto.SpareParts.ToList();

            foreach (var user in dataLog)
            {
                //  var typeEdtion = (user.TypeEdtion.ToUpper().Equals("MINUS")) ? "OUT" : "IN";
                builder.AppendLine($"{user.PartNumber};{user.Quantity};{user.Location};{user.UserId}");
            }

            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "spare-parts.csv");
        }
    }
}

Controllers/SpareRepairersController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BIRC.Models;
using BIRC.Models.Entities;
using BIRC.Helper;
using System.Linq;
using System.Text;

namespace BIRC.Controllers
{
    public class SpareRepairersController : Controller
    {
        private readonly Contexto _contexto;
        protected readonly QueryHelper<SpareRepairer> _helper;

        public SpareRepairersController(Contexto context)
        {
            _contexto = context;
            _helper = new QueryHelper<SpareRepairer>(context);
        }

        // GET: SpareRepairers
        public IActionResult Index()
        {
            var sparerepairers = _contexto.SpareRepairer.OrderByDescending(x => x.Id).ToList();
            return View(sparerepairers);          
        }

        [HttpPost]
        public ActionResult Index(string searchString, string search)
        {
            //var spare = from s in _contexto.SpareParts select s;
            var recebeSearch = search;

            if (String.IsNullOrEmpty(searchString))
            {
                return RedirectToAction("Index");
            }
            if (searchString.Equals("ProductName"))
            {
                var spare = _contexto.SpareRepairer.Where(s => s.ProductName.Contains(search)).ToList();
                return View(spare);
            }

            return View();

        }

       /* // GET: SpareRepairers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spareRepairer = await _contexto.SpareRepairer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spareRepairer == null)
            {
                return NotFound();
            }

            return View(spareRepairer);
        }*/

        // GET: SpareRepairers/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: SpareRepairer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SpareRepairer spareRepairer)
        {
            try
            {
                string producName= spareRepairer.ProductName.ToUpper();
                string description = spareRepairer.DescProduct.ToUpper();
                
                spareRepairer.ProductName= producName;
                spareRepairer.DescProduct= description;

                if (ModelState.IsValid)
                {
                    spareRepairer.Id = _helper.GetMaxId();
                    _contexto.SpareRepairer.Add(spareRepairer);
                   _contexto.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(spareRepairer);
            }
            catch
            {
                return View();
            }
        }

        // GET: SpareRepairers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spareRepairer = await _contexto.SpareRepairer.FindAsync(id);
            if (spareRepairer == null)
            {
                return NotFound();
            }
            return View(spareRepairer);
        }

        //POST: SpareRepairers/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, string dtIn, string dtValidate, string partNumber, string description,
            string quantity,string minimumQuantity, string location, string value, string po, string typeedtion, string unitMeasure, string typeOperation, string localUsed,string userId)
        {
            int qtyFormated = 0;

            if (typeedtion.Equals("minus"))
            {
                qtyFormated = int.Parse(value) - int.Parse(quantity);
            }
            else
            {
                qtyFormated = int.Parse(value) + int.Parse(quantity);
            }           

            SpareRepairer spareRepairer = new SpareRepairer
            {
                Id = int.Parse(id),
                ProductName = partNumber.ToUpper().ToString(),
                DescProduct = description,
                Quantity = qtyFormated,
                minimumQuantity = int.Parse(minimumQuantity),//implementado 060323
                PurchaseOrder = po,
                StorageBin = location,
                UnitMeasure = unitMeasure,
                TypeOperation = typeOperation,
                DtIn = DateTime.Parse(dtIn),
                DtValidate = DateTime.Parse(dtValidate),
                LocalUsed= localUsed,
                UserId = userId
            };

            LogUpdate logUpdate = new LogUpdate
            {
                Id = int.Parse(id),
                Alteration = DateTime.Now,
                Quantity = int.Parse(quantity),
                minimumQuantity = int.Parse(minimumQuantity),//implementado 060323
                Product = partNumber,
                TypeEdtion = typeedtion,
                UserId = userId,
                CurrentBalance = qtyFormated,
                LocalUsed= localUsed,
                ModelAlteration = "SpareRepairer"

            };

            if (ModelState.IsValid)
            {
                if (id != null)
                {
                    _contexto.Update(spareRepairer);
                    _contexto.SaveChangesAsync();
                    _contexto.LogUpdate.AddAsync(logUpdate);
                    _contexto.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else return View(spareRepairer);
            }
            return NotFound();
        }

        // GET: SpareRepairers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spareRepairer = await _contexto.SpareRepairer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spareRepairer == null)
            {
                return NotFound();
            }

            return View(spareRepairer);
        }

        // POST: SpareRepairers/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var spareRepairer = await _contexto.SpareRepairer.FindAsync(id);
            _contexto.SpareRepairer.Remove(spareRepairer);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
              
        private bool SpareRepairerExists(int id)
        {
            return _contexto.SpareRepairer.Any(e => e.Id == id);
        }

        public IActionResult Csv()
        {
            var builder = new StringBuilder();

            builder.AppendLine("PRODUCT NAME;QUANTITY;LOCATION;USUARIO");

            var dataLog = _contexto.SpareRepairer.ToList();

            foreach (var user in dataLog)
            {
                //  var typeEdtion = (user.TypeEdtion.ToUpper().Equals("MINUS")) ? "OUT" : "IN";
                builder.AppendLine($"{user.ProductName};{user.Quantity};{user.StorageBin};{user.UserId}");
            }

            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "spare-unproductive.csv");
        }
    }
}

Views/SpareParts/Create.cshtml
@model BIRC.Models.Entities.SpareParts
@{
    ViewData["Title"] = "Create";
}

<h2>Register new item</h2>
<hr />

<style>
    input {
        text-transform: uppercase;
    }
</style>

<form asp-action="Create" method="post">

    <div class="form-row">

        <div class="col-md-4 mb-3">
            <label asp-for="PartNumber" class="control-label"></label>
            <input asp-for="PartNumber" class="form-control" />
        </div>

        <div class="col-md-4 mb-3">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
        </div>

        <div class="col-md-2 mb-3">
            <label asp-for="Quantity" class="control-label"></label>
            <input asp-for="Quantity" type="number" class="form-control" maxlength="999999" min="0" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <div class="col-md-2 mb-3">
            <label asp-for="minimumQuantity" class="control-label"></label>
            <input asp-for="minimumQuantity" type="number" class="form-control" maxlength="999999" min="0"/>
            <span asp-validation-for="minimumQuantity" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="Location" class="control-label"> </label>
            <select asp-for="Location" class="custom-select" required>
                <option selected>Select Location...</option>
                <option>
                    ARMARIO SPARE PARTS
                </option>
            </select>
            <span asp-validation-for="Location" class="text-danger"></span>

        </div>

        <div class="col-md-3 mb-3">
            <label asp-for="DtIn" class="control-label">Date In</label>
            <input asp-for="DtIn" class="form-control" />
            <span asp-validation-for="DtIn" class="text-danger"></span>
        </div>

    </div>

    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label asp-for="PurchaseOrder" class="control-label">Purchase Order</label>
            
            <input asp-for="PurchaseOrder" type="number" class="form-control"  maxlength="15" min="0" />
        </div>
    </div>

    <input type="submit" value="Save" class="btn btn-primary" style="padding-top:10px" />

</form>


<div style="padding-top:10px">
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SpareParts/EditItem.cshtml
@model BIRC.Models.Entities.SpareParts

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Unit</h1>

<h4>SpareParts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditItem" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
             
            <div class="form-group">
                <label asp-for="PartNumber" class="control-label"></label>
                <input asp-for="PartNumber" class="form-control" readonly />
                <span asp-validation-for="PartNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" readonly />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Quantity" for="inputvalue"></label>
                <input asp-for="Quantity" type="number" class="form-control" id="inputvalue"  max="1000" min="0">
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtIn" class="control-label"></label>
                <input asp-for="DtIn" class="form-control" readonly />
                <span asp-validation-for="DtIn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" readonly />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurchaseOrder" class="control-label"></label>
                <input asp-for="PurchaseOrder" class="form-control" readonly />
                <span asp-validation-for="PurchaseOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalUsed" class="control-label"></label>
                <input asp-for="LocalUsed" class="form-control" readonly />
                <span asp-validation-for="LocalUsed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" readonly />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
                <input asp-for="Id" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SpareParts/ReportGeral.cshtml
@model BIRC.ViewModels.ReportGeralViewModel
@{
    ViewData["Title"]="Reports All";
}
<h3 style="color:black">@ViewData["Title"]</h3>
<hr />

<div class="row">
    <div class="divbtn">
        <a class="btnreport btn1 form-control" style="text-decoration:none" asp-action="Csv" asp-controller="SpareChemical">Chemical</a>
    </div>

    <div class="divbtn">
        <a class="btnreport btn2 form-control" style="text-decoration:none" asp-action="Csv" asp-controller="SpareParts">Stations</a>
    </div>

    <div class ="divbtn">
        <a class="btnreport btn3 form-control " style="text-decoration:none" asp-action="Csv" asp-controller="SpareRepairers">Unproductive</a>
    </div>    
   
    <div class="divbtn">
        <a class="btnreport btn4 form-control" style="text-decoration:none" asp-action="Csv" asp-controller="SpareOffice"> Office</a>
    </div >

    <div class="divbtn">
        <a class="btnreport btn5 form-control" style="text-decoration:none" asp-action="Csv" asp-controller="LogUpdate">Report Geral</a>
    </div>   
</div>
<hr />
<div style="padding-top:10px">
    <a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Views/SpareParts/SpareMenu.cshtml
@{
    ViewData["Title"] = "Spare Menu";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />


<h3 style="opacity:0,4; color:#808080" class="text-center">RCB ADVANCE MANAGMENT</h3>

<div style="display:inline-block">
    <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Back to List</a>
   
</div>

<hr />
<br />


<div class="row">
    <div class="col-lg-3">
        <a asp-action="Index" asp-controller="SpareChemical" style="text-decoration:none" class="align-content-center">
            <div class="card" style="height:200px">
                <div class="card-body">
                    <h3 style="text-align:center">Chemical </h3>
                    <div style="text-align:center" class="card-body">
                        <i class="fas fa-flask" id="icon"></i>
                    </div>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3">     
        <a asp-action="Index" asp-controller="SpareParts" style="text-decoration:none" class="align-content-center">
            <div class="card1" style="height:200px">
                <div class="card-body">
                    <h3 style="text-align:center">Stations</h3>
                    <div style="text-align:center" class="card-body">
                        <i id="icon" class="fas fa-server"></i>
                    </div>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3">
        <a asp-action="Index" asp-controller="SpareRepairers" style="text-decoration:none" class="align-content-center">
            <div class="card2" style="height:200px">
                <div class="card-body">
                    <h3 style="text-align:center">Unproductive</h3>
                    <div style="text-align:center" class="card-body">
                        <i id="icon" class="fas fa-microscope"></i>
                    </div>
                </div>
            </div>
        </a>
    </div>

    <div class="col-lg-3">
        <a asp-action="Index" asp-controller="SpareOffice" style="text-decoration:none" class="align-content-center">
            <div class="card3" style="height:200px">
                <div class="card-body">
                    <h3 style="text-align:center">Office</h3>
                    <div style="text-align:center" class="card-body">
                        <i id="icon" class="fas fa-laptop"></i>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>

Views/SpareParts/ViewLogUpdate.cshtml
@model IEnumerable<BIRC.Models.Entities.LogUpdate>
@{
    ViewData["Title"] = "View Log Report";
}

<h3 style="opacity:0,4; color:#808080" class="text-center">Stock Movement</h3>
<hr />

<div style="display:inline-block">
    <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Back to List</a>
</div>

<div id="messageStatus" class="alert alert-success" role="alert" style="display: none;" messageAlert>
    <span message></span>
</div>

<hr class="container" />

<div class="table-responsive-md" style="">
    <table border="1" class="table table-sm table-hover border">
        <thead>
            <tr class="text-center bg-primary" style="color:white;white-space:nowrap">
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>                
                <th>
                    @Html.DisplayNameFor(model => model.Alteration)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.minimumQuantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TypeEdtion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ModelAlteration)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentBalance)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LocalUsed)
                </th>



            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr style="white-space:nowrap; text-transform: uppercase; font-size:13px;">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.Alteration)
                    </td>
                    <td style="white-space:nowrap">
                        @Html.DisplayFor(modelItem => item.Product)
                    </td>
                    <td item-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.minimumQuantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeEdtion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModelAlteration)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentBalance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocalUsed)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<br/>
<form asp-action="Export" asp-controller="SpareParts" class="form-inline" method="post">   

    <div class="form-group report">
        <input type="submit" class="btn btn-primary" value="Get Report" />
    </div>

</form>